#!/usr/bin/env python3
"""Generate the twelve chess piece SVGs.

The artwork is authored here rather than taken from a set found elsewhere, so
its provenance is not a thing anyone has to take on trust: the shapes are in
this file, and running it reproduces the assets exactly. That is what allows
the project to be licensed permissively without asking anyone's permission.

Each piece is one silhouette, drawn once, emitted twice -- light pieces are a
pale fill with a dark outline, dark pieces the reverse. Shapes are deliberately
plain: they have to stay recognisable at forty pixels on a board, where fine
detail turns into mud.

    python3 packaging/generate-pieces.py assets/pieces
"""

from __future__ import annotations

import pathlib
import sys

SIZE = 64

# Every piece stands on the same foot, which is what makes the set look like a
# set rather than six unrelated drawings.
FOOT = "M 13 57 L 51 57 L 47.5 50 L 16.5 50 Z"
COLLAR = "M 18 50 L 46 50 L 43.5 44.5 L 20.5 44.5 Z"

# Body shapes, from the collar upwards. Drawn in a 64x64 box with the piece
# occupying roughly y=6 to y=57.
# Bodies may reference {accent}, which is filled in with the outline colour.
BODIES: dict[str, str] = {
    "pawn": (
        '<circle cx="32" cy="17.5" r="7.5"/>'
        '<path d="M 26 24 C 26 31 22.5 37 20.5 44.5 L 43.5 44.5 '
        'C 41.5 37 38 31 38 24 Z"/>'
    ),
    "rook": (
        '<path d="M 15 12 L 15 23 L 20 23 L 20 17 L 26.5 17 L 26.5 23 '
        "L 37.5 23 L 37.5 17 L 44 17 L 44 23 L 49 23 L 49 12 L 42 12 "
        "L 42 16 L 36 16 L 36 12 L 28 12 L 28 16 L 22 16 L 22 12 Z\"/>"
        '<path d="M 19.5 23 L 17.5 44.5 L 46.5 44.5 L 44.5 23 Z"/>'
    ),
    "knight": (
        '<path d="M 23 44.5 C 23 37 25 32 29.5 28.5 '
        "C 26 28.5 23.5 27 22.5 24 L 27 20 "
        "C 28.5 15.5 33 11 38.5 10.5 L 40.5 6.5 L 43.5 11.5 "
        "C 47.5 15.5 48.5 24 47.5 32 C 46.5 39 45.5 41 45.5 44.5 Z\"/>"
        # The eye takes the outline colour so it reads on either piece. Named
        # explicitly rather than with context-stroke, which is SVG 2 and not
        # something every renderer supports.
        '<circle cx="37" cy="19" r="1.9" fill="{accent}" stroke="none"/>'
    ),
    "bishop": (
        '<circle cx="32" cy="10.5" r="4"/>'
        '<path d="M 32 14 C 40.5 18.5 43 27 40.5 36 L 23.5 36 '
        'C 21 27 23.5 18.5 32 14 Z"/>'
        '<path d="M 32 19.5 L 32 27 M 28.5 23.5 L 35.5 23.5" '
        'stroke-width="2.2" fill="none"/>'
        '<path d="M 22 44.5 L 42 44.5 L 40.5 36 L 23.5 36 Z"/>'
    ),
    "queen": (
        '<path d="M 18.5 44.5 L 15 21 L 22.5 30 L 27 16.5 L 32 28 '
        'L 37 16.5 L 41.5 30 L 49 21 L 45.5 44.5 Z"/>'
        '<circle cx="15" cy="18.5" r="3.4"/>'
        '<circle cx="27" cy="14" r="3.4"/>'
        '<circle cx="37" cy="14" r="3.4"/>'
        '<circle cx="49" cy="18.5" r="3.4"/>'
    ),
    # A crown with a band, not just a dome -- without the band it reads as a
    # bishop that has lost its slit, which is the one confusion that actually
    # matters on a board.
    "king": (
        # The cross is a filled outline, not two strokes. Drawn as strokes it
        # takes the outline colour, and the dark piece's outline is pale -- so
        # the cross vanished on pale squares, which is where the black king
        # spends half its life.
        #
        # Its arms are seven units wide for the same reason the balls below are
        # not tiny: a shape narrower than twice the stroke width has no
        # interior left to show, so it reads as an outline of nothing rather
        # than as a piece-coloured cross.
        '<path d="M 28.5 2.5 L 35.5 2.5 L 35.5 8 L 41 8 L 41 15 '
        'L 35.5 15 L 35.5 20.5 L 28.5 20.5 L 28.5 15 L 23 15 L 23 8 '
        'L 28.5 8 Z"/>'
        '<path d="M 20 44.5 C 16 33 21.5 25 32 20.5 '
        'C 42.5 25 48 33 44 44.5 Z"/>'
        '<path d="M 21.5 35 L 42.5 35" stroke-width="2.4" fill="none"/>'
    ),
}

TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  {name}, {colour}.

  Generated by packaging/generate-pieces.py. Edit that, not this.
  Original artwork for this project; see LICENSE.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}"
     viewBox="0 0 {size} {size}">
  <g fill="{fill}" stroke="{stroke}" stroke-width="{width}"
     stroke-linejoin="round" stroke-linecap="round">
    {body}
    <path d="{collar}"/>
    <path d="{foot}"/>
  </g>
</svg>
"""

# A near-white rather than pure white, and a near-black rather than pure black,
# so neither piece disappears into a light or dark square.
STYLES = {
    "white": {"fill": "#F7F6F2", "stroke": "#1A1C1E", "width": "2.4"},
    "black": {"fill": "#25282C", "stroke": "#EDEDEA", "width": "1.8"},
}


def main() -> int:
    target = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "assets/pieces")
    target.mkdir(parents=True, exist_ok=True)

    for name, body in BODIES.items():
        for colour, style in STYLES.items():
            svg = TEMPLATE.format(
                name=name,
                colour=colour,
                size=SIZE,
                body=body.format(accent=style["stroke"]),
                collar=COLLAR,
                foot=FOOT,
                **style,
            )
            (target / f"{name}_{colour}.svg").write_text(svg)

    print(f"wrote {len(BODIES) * len(STYLES)} pieces to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
